### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by superchun** [johntmcintosh/xcunsign#4]
if I run xcunsign 8.0, the iterm will show : too many levels of symbolic links: xcunsign

**Comment by johntmcintosh** [comment]
@cconecode, I believe that often indicates that the symbolic link was setup using a relative path rather than an absolute path. Try deleting the symlink and recreating using absolute paths for both the source and destination. If that works for you, let me know and I can update the readme to highlight that distinction for others.

**Comment by superchun** [comment]
@johntmcintosh yeah,it's works for me, thank you very much!
